test:
  name: test.test
  age: ${random.int(10,100)}
  address: shanghai
server:
  port: 8086
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=UTF-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/

  datasource:
      url: jdbc:mysql://localhost:30306/example_db
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver


